stages:
- build-backend
- build-frontend
- test-backend
- test-frontend
- deploy-backend
- deploy-frontend
- send-coverage
env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_API_LEVEL_UI_TESTS=21
  - ANDROID_BUILD_TOOLS_VERSION_UI_TESTS=21.0.3
jobs:
  include:
  - stage: build-backend
    language: java
    script:
    - "(cd backend/; ./gradlew assemble)"
  - stage: build-frontend
    language: android
    android:
      components:
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - android-$ANDROID_API_LEVEL
    script:
    - "(cd frontend/; ./gradlew assembleDebug)"
  - stage: test-backend
    language: java
    script:
    - cd backend/
    - "./gradlew test clean"
  - stage: test-frontend
    language: android
    android:
      components:
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION_UI_TESTS
      - android-$ANDROID_API_LEVEL_UI_TESTS
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - android-$ANDROID_API_LEVEL
      - add-on
      - extra
      - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL_UI_TESTS
    before_script:
    - cd frontend/
    - android list targets
    - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL_UI_TESTS
      --abi default/armeabi-v7a
    - emulator -avd test -no-window &
    - android-wait-for-emulator
    - adb shell settings put global window_animation_scale 0 &
    - adb shell settings put global transition_animation_scale 0 &
    - adb shell settings put global animator_duration_scale 0 &
    - adb shell input keyevent 82 &
    script:
    - "./gradlew test"
    - "./gradlew clean connectedCheck"
  - stage: deploy-backend
    if: branch = master
    language: java
    services:
    - docker
    provider: heroku
    script:
    - cd backend/
    - "./gradlew build docker"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PW
    - docker push commonplayground/commonplayground
    - docker logout
    - heroku container:login
    - docker tag commonplayground/commonplayground:latest registry.heroku.com/commonplayground/web
    - docker push registry.heroku.com/commonplayground/web
    - heroku container:release web -a commonplayground
  - stage: deploy-frontend
    if: branch = master
    language: android
    android:
      components:
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - android-$ANDROID_API_LEVEL
    script:
    - cd frontend/
    - openssl aes-256-cbc -K $encrypted_ba187bd0e4a1_key -iv $encrypted_ba187bd0e4a1_iv
      -in ../keystore.jks.enc -out keystore.jks -d
    - "./gradlew assembleRelease"

  - stage: send-coverage
    language: java
    script:
    - cd backend/
    - "./gradlew build"
    - "./gradlew jacocoTestReport"
    - "./gradlew sendCoverageToCodacy"
    
before_deploy:
  - echo "Start Frontend Deployment"
  - export APP_VERSION_RAW=$(./gradlew :app:printVersionName --warning-mode=none)
  - export APP_VERSION="$(echo $APP_VERSION_RAW | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/')"
  - echo $APP_VERSION

deploy:
  provider: releases
  api_key:
    secure: BRN+/GjSJvwH3rn3MK8harchvtW57Qi/+bJANjP+1Qg+qS0xnxmFDYtUUU1nU3O2yXBsdJLbyIsx9MrID01L0YBT8kYw5JfuayyVlaQzqa+ibZ2WLGMcmS/sKHoGtBXCnG9/wWfqa+hXvxUBTPxo9JRU8P2dIpT49yPcJC+V7ZDMj2YiCe7odbwI/ixjUVIfsk59RcnvbhdyTSd2w0vbGwHyd4Yb6W4Hh1ICWIivWhaafp4lwPa4xObeKUyTOWP7cxEMUIwatQbEK3eX91QcrQiloMPrNem1zoL3q62KeoJMmcixSp7fixtxAY461u/ezVlAsc7tVVW79ytoGCq17fMQJf9jHDeWd8RBIEhaq2uhmI/Evy6cKYYFJyzjk5U1lyxHe05vWRF6F9ZQQvl3v8pmBkJtfVik5/AWDmUayk80VUW5K/VyUEmeMdU8R5d+rGIlju9r787SsE+rgcKYbgjSARMx39N22umEg1z7QZMsBFyoKaYtPZrLCviwExF5Bj5S+RqbjMCmMqyrnOx5vumtzKld3LYAcKDJM4SyLmqa8+KDZ4FuwCH7uv+22tSr2vypoGeE+Zug5trhrAURyHVRAnLswntQ3SDVlX4Yxf6uuGAh0ZSTJrBvKjWRkxOwf4yRq2q/Zj8qxRpRjn1qU/zPWv3TCDcn2BAzMe1KpCU=
  file: app/build/outputs/apk/release/app-release.apk
  file_glob: true
  skip_cleanup: true
  overwrite: true
  name: "$APP_VERSION"
  tag_name: "$APP_VERSION"
  on:
    repo: nilskre/CommonPlayground
    branch: master