stages:
  - build-backend
  - build-frontend
  - test-backend
  - test-frontend
  - deploy-backend
  - deploy-frontend

env:
 global:
    - ANDROID_API_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=24.0.3

jobs:
  include:
    - stage: build-backend
      language: java
      script:
        - (cd backend/; ./gradlew assemble)
    - stage: build-frontend
      language: android
      android:
        components:
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - android-$ANDROID_API_LEVEL
      script:
        - (cd frontend/; ./gradlew assembleDebug)

    - stage: test-backend
      language: java
      script:
        - (cd backend/; ./gradlew test clean)
    - stage: test-frontend
      language: android
      android:
        components:
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - android-$ANDROID_API_LEVEL
          - add-on
          - extra
          - sys-img-armeabi-v7a-android-24
      before_script:
        - cd frontend/
        - android list targets
        - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi default/armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
      script:
        - (cd frontend/; ./gradlew build connectedCheck)

    - stage: deploy-backend
      if: branch = master
      language: java
      script:
        - echo "Deployment-Backend"
    - stage: deploy-frontend
      if: branch = master
      language: android
      android:
        components:
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - android-$ANDROID_API_LEVEL
      script:
        - echo "Deployment-Frontend"
