stages:
  - build-backend
  - build-frontend
  - test-backend
  - test-frontend
  - deploy-backend
  - deploy-frontend

env:
 global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_API_LEVEL_UI_TESTS=21
    - ANDROID_BUILD_TOOLS_VERSION_UI_TESTS=21.0.3

jobs:
  include:
    - stage: build-backend
      language: java
      script:
        - (cd backend/; ./gradlew assemble)
    - stage: build-frontend
      language: android
      android:
        components:
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - android-$ANDROID_API_LEVEL
      script:
        - (cd frontend/; ./gradlew assembleDebug)

    - stage: test-backend
      language: java
      script:
        - (cd backend/; ./gradlew test clean)
    - stage: test-frontend
      language: android
      android:
        components:
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION_UI_TESTS
          - android-$ANDROID_API_LEVEL_UI_TESTS
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - android-$ANDROID_API_LEVEL
          - add-on
          - extra
          - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL_UI_TESTS
      before_script:
        - cd frontend/
        - android list targets
        - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL_UI_TESTS --abi default/armeabi-v7a
        - emulator -avd test -no-window &
        - android-wait-for-emulator
        - adb shell settings put global window_animation_scale 0 &
        - adb shell settings put global transition_animation_scale 0 &
        - adb shell settings put global animator_duration_scale 0 &
        - adb shell input keyevent 82 &
      script:
        - (cd frontend/; ./gradlew build connectedCheck)

    - stage: deploy-backend
      #if: branch = master
      language: java
      services:
        - docker
      provider: heroku
      api_key:
        secure: cc24LtHFrFQDORKxGhVKo2Em2gG+WS/4J9MtE94B2PhtuqyBH90Tjd2xUQXRT2w5EdxlLNcS/spYq4rG0duhFvff0oJf1Zkf7YNSNY2097/b3OFKBH0KoqqFfN/OxoXBQT0eryhRmQD7hsQUDxoRCHcOsERnn0y3y9Zq+eDIVUn8wneREcE0EjG1qYPpvrO0kUzsEAjH6qixW8rCyZET5KHcCV1/78ZddbsYj3Hz+8yqgss4e2rpOy9HAlikQdSh9wuwPgHcW8HbSZVOMo+BFvmnqFcI+pcOLTK6VNduqBkBsD4arftv2oqM0J5uJmrTTaHt0zpuDSQwd03kz2I10MwQgOy6AhZNnB/1tCugd7HNdvT823FeBR76z/tveKfvqH6ErqKnjs7TFR6jBIAo5IROLbOSF714ua3o4tKwU/uqSqn4Ks/C72HA7dsiUThngqu+mcoFmUJIXJhuJfBQ2vYU1o04QDAkJRwhZ7nnfJzp+f6MhvxwICQQzkCQros4ooBofhpgA5CIb8oeYUhinA+2qSxeZx238vJTaWQkGYoFjvTp32H312nl26VwJC7L8JTX0m9gWdH8STHlLuvI6nZHrwTSSHiqW5lpteQd0pbzvNvNSuss3ZeLvpVvyjYWVMXWGAGhpeoBmp3cUc6ZbZz2wm5SqmjC8qNFE+mrSf0=
      script:
        - printf "machine api.heroku.com \n  login $LOGIN_EMAIL \n  password $LOGIN_PWD \nmachine git.heroku.com \n  login $LOGIN_EMAIL \n  password $LOGIN_PWD" > ~/.netrc
        - cd backend/ 
        - ./gradlew build docker
        - heroku login
        - heroku container:login
        - docker tag commonplayground/commonplayground:latest registry.heroku.com/commonplayground/web
        - docker push registry.heroku.com/commonplayground/web
        - heroku container:release web -a commonplayground
    - stage: deploy-frontend
      if: branch = master
      language: android
      android:
        components:
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - android-$ANDROID_API_LEVEL
      script:
        - echo "Deployment-Frontend"
