language: java

stages:
  - build-backend
  - build-frontend
  - test-backend
  - test-frontend
  - deploy-backend
  - deploy-frontend

jobs:
  include:
    - stage: build-backend
      script:
        - chmod +x ./gradlew
        - (cd backend/; ./gradlew assemble)
    - stage: build-frontend
      script:
        - chmod +x ./gradlew
        - (cd frontend/; ./gradlew assembleDebug)

    - stage: test-backend
      script:
        - echo "Test-Backend"
    - stage: test-frontend
      script:
        - echo "Test-Frontend"

    - stage: deploy-backend
      script:
        - echo "Deployment-Backend"
    - stage: deploy-frontend
      script:
        - echo "Deployment-Frontend"

